routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware('auth')->group(function () {
  Route::get('payrolls/payment_detail_pdf/{id}', [App\Http\Controllers\PayrollController::class, 'paymentDetailPdf'])->name('payrolls.payment_detail_pdf');
  Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('index');
  Route::resource('employees', App\Http\Controllers\EmployeeController::class);
  Route::resource('positions', App\Http\Controllers\PositionController::class);
  Route::get('payrolls/add/{id}', [App\Http\Controllers\PayrollController::class, 'addPayroll'])->name('payrolls.add');
  Route::post('payrolls/pay_salary/{id}', [App\Http\Controllers\PayrollController::class, 'paySalary'])->name('payrolls.pay_salary');
  Route::get('payrolls/payment_detail_pdf/{id}', [App\Http\Controllers\PayrollController::class, 'paymentDetailPdf'])->name('payrolls.payment_detail_pdf');
  Route::resource('payrolls', App\Http\Controllers\PayrollController::class);
  Route::resource('attendances', App\Http\Controllers\AttendanceController::class);
});

app/Models/Position.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function employees()
    {
        return $this->belongsToMany(Employee::class, 'employee_position', 'position_id', 'employee_id')
            ->withTimestamps();
    }
}

app/Http/Controllers/PositionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Position;
use Illuminate\Http\Request;

class PositionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $positions = Position::all();
        return view('position.index', compact('positions'));
    }

    public function create()
    {
        return view('position.create');
    }

    public function store(Request $request)
    {
        Position::create([
            'name' => $request->name,
            'base_salary' => $request->base_salary,
            'overtime_cost' => $request->overtime_cost,
        ]);

        session()->flash('success', 'Position created successfully.');
        return redirect()->route('positions.index');
    }

    public function edit($id)
    {
        $position = Position::find($id);
        return view('position.edit', compact('position'));
    }

    public function update($id, Request $request)
    {
        $position = Position::find($id);
        $position->name = $request->name;
        $position->base_salary = $request->base_salary;
        $position->overtime_cost = $request->overtime_cost;
        $position->save();

        session()->flash('success', 'Position edited successfully.');
        return redirect()->route('positions.index');
    }

    public function destroy($id)
    {
        $position = Position::find($id);
        $position->delete();

        return redirect()->route('positions.index');
    }
}

resources/views/position/create.blade.php
@extends('layout')
@section('title', 'Add New Position')
@section('content')
<div class="col-sm-12 col-xl-12">
  <div class="bg-secondary rounded h-100 p-4">
    <h6 class="mb-4"> Add New Position</h6>
    <form method="POST" action="{{route('positions.store')}}">
      @csrf
      {{ method_field('POST') }}
      {{ csrf_field() }}
      <div class="mb-3">
        <label for="name" class="form-label">Position Name</label>
        <input type="text" class="form-control" id="name" name="name">
      </div>
      <div class="mb-3">
        <label for="baseSalary" class="form-label">Base Salary</label>
        <input type="number" class="form-control" id="baseSalary" name="base_salary">
      </div>
      <div class="mb-3">
        <label for="overtimeCost" class="form-label">Overtime Cost</label>
        <input type="number" class="form-control" id="overtimeCost" name="overtime_cost">
      </div>
      <button type="submit" class="btn btn-primary">Save Position</button>
    </form>
  </div>
</div>
@endsection

resources/views/position/edit.blade.php
@extends('layout')
@section('title', 'Edit New Position')
@section('content')
<div class="col-sm-12 col-xl-12">
  <div class="bg-secondary rounded h-100 p-4">
    <h6 class="mb-4"> Edit Position</h6>
    <form method="POST" action="{{route('positions.update', $position->id)}}">
      @csrf
      {{ method_field('PUT') }}
      {{ csrf_field() }}
      <div class="mb-3">
        <label for="name" class="form-label">Position Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{$position->name}}">
      </div>
      <div class="mb-3">
        <label for="baseSalary" class="form-label">Base Salary</label>
        <input type="number" class="form-control" id="baseSalary" name="base_salary" value="{{$position->base_salary}}">
      </div>
      <div class="mb-3">
        <label for="overtimeCost" class="form-label">Overtime Cost</label>
        <input type="number" class="form-control" id="overtimeCost" name="overtime_cost" value="{{$position->overtime_cost}}">
      </div>
      <button type="submit" class="btn btn-primary">Update Position</button>
    </form>
  </div>
</div>
@endsection

resources/views/position/index.blade.php
@extends('layout')
@section('title', 'Position List')
@section('content')
<div class="col-sm-12 col-xl-12" style="margin-bottom: 10px;">
  <div class="bg-secondary rounded h-100 p-4">
    <a href="{{route('positions.create')}}" class="btn btn-light m-2">
      <i class="fa fa-plus"></i> Add New Position
    </a>
  </div>
</div>
<div class="text-center rounded p-4"  style="background-color:whitesmoke;">
  <div class="d-flex align-items-center justify-content-between mb-4">
    <h6 class="mb-0" style="color: slategray;">Position List</h6>
  </div>
  <div class="table-responsive">
    <table class="table text-start align-middle table-hover mb-0 my-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Base Salary</th>
          <th>Overtime Cost</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($positions as $position)
        <tr>
          <td>{{$position->name}}</td>
          <td>{{$position->base_salary}}</td>
          <td>{{$position->overtime_cost}}</td>
          <td>
            <a class="btn btn-success btn-sm" href="{{ route('positions.show', $position->id) }}">
              <i class="fa fa-eye"></i>
            </a>
            <a class="btn btn-warning btn-sm" href="{{ route('positions.edit', $position->id) }}">
              <i class="fa fa-edit"></i>
            </a>
            <form style="display: inline-block;" method="POST" onsubmit="return confirm('Apakah kamu yakin untuk menghapus data ini?')" action="{{route('positions.destroy', $position->id)}}">
              {{ csrf_field() }}
              {{ method_field('DELETE') }}
              <button type="submit" class="btn btn-danger btn-sm">
                <i class="fa fa-trash"></i>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection

@push('scripts')
@if(session('success'))
<script>
  Swal.fire({
    icon: 'success',
    title: 'Success',
    text: "{{ session('success') }}",
  });
</script>
@endif
<script>
  $(document).ready(function() {
    $('.my-table').DataTable();
  });
</script>
@endpush