routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware('auth')->group(function () {
  Route::get('payrolls/payment_detail_pdf/{id}', [App\Http\Controllers\PayrollController::class, 'paymentDetailPdf'])->name('payrolls.payment_detail_pdf');
  Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('index');
  Route::resource('employees', App\Http\Controllers\EmployeeController::class);
  Route::resource('positions', App\Http\Controllers\PositionController::class);
  Route::get('payrolls/add/{id}', [App\Http\Controllers\PayrollController::class, 'addPayroll'])->name('payrolls.add');
  Route::post('payrolls/pay_salary/{id}', [App\Http\Controllers\PayrollController::class, 'paySalary'])->name('payrolls.pay_salary');
  Route::get('payrolls/payment_detail_pdf/{id}', [App\Http\Controllers\PayrollController::class, 'paymentDetailPdf'])->name('payrolls.payment_detail_pdf');
  Route::resource('payrolls', App\Http\Controllers\PayrollController::class);
  Route::resource('attendances', App\Http\Controllers\AttendanceController::class);
});

app/Models/Payroll.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Payroll extends Model
{
    use HasFactory;

    public function employeePosition()
    {
        return $this->belongsTo(EmployeePosition::class);
    }

    public function calculateTotalSalary($absen, $base_salary, $overtime_hours, $overtime_cost, $bonus_salary, $deduction)
    {
        $total_absen = $absen/20 * $base_salary;
        $total_overtime = $overtime_hours * $overtime_cost;
        $total_salary = $base_salary + $total_overtime + $bonus_salary - $total_absen - $deduction;

        return $total_salary;
    }
}

app/Http/Controllers/PayrollController.php
<?php

namespace App\Http\Controllers;

use App\Models\EmployeePosition;
use App\Models\Payroll;
use App\Models\Position;
use Carbon\Carbon;
use Dompdf\Dompdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;

class PayrollController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if (Auth::user()->role == 'admin') {
            $employee_positions = EmployeePosition::with('position', 'employee')->get();
        } else {
            $employee_positions = EmployeePosition::with('position','employee')->where('employee_id', Auth::user()->employee_id)->get();
        }
        return view('payroll.index', compact('employee_positions'));
    }

    public function addPayroll($id)
    {
        $employee_position = EmployeePosition::find($id);
        return view('payroll.create', compact('employee_position'));
    }

    public function show($id)
    {
        $payrolls = Payroll::with('employeePosition')->where('employee_position_id', $id)->get();
        $first_payroll = Payroll::with('employeePosition')->where('employee_position_id', $id)->first();
        return view('payroll.show', compact('payrolls', 'first_payroll'));
    }

    public function store(Request $request)
    {
        $payroll = new Payroll();
        $payroll->status = 'pending';
        $payroll->month = $request->month;
        $payroll->year = $request->year;
        $payroll->deduction = $request->deduction;
        $payroll->absen = $request->absen;
        $payroll->present = $request->present;
        $payroll->employee_position_id = $request->employee_position_id;
        $payroll->overtime_hours = $request->overtime_hours;
        $payroll->bonus_salary = $request->bonus_salary;

        $position_id = EmployeePosition::find($payroll->employee_position_id)->position_id;
        $base_salary = Position::find($position_id)->base_salary;
        $overtime_cost = Position::find($position_id)->overtime_cost;
        $totalSalary = $payroll->calculateTotalSalary(
            $payroll->absen,
            $base_salary,
            $payroll->overtime_hours,
            $overtime_cost,
            $payroll->bonus_salary,
            $payroll->deduction
        );

        $payroll->total_salary = $totalSalary;
        $payroll->save();
        session()->flash('success', 'Payroll created successfully.');
        return redirect()->route('payrolls.index');
    }

    public function paySalary($id)
    {
        $payroll = Payroll::find($id);
        $payroll->status = 'paid';
        $payroll->payment_date = Carbon::now();
        $payroll->save();

        return redirect()->back();
    }

    public function paymentDetailPdf($id)
    {
        $payroll = Payroll::find($id);
        $base_salary = $payroll->employeePosition->position->base_salary;
        $overtime_hours = $payroll->overtime_hours;
        $absen = $payroll->absen;
        $bonus_salary = $payroll->bonus_salary;
        $overtime_cost = $payroll->employeePosition->position->overtime_cost;
        $total_salary = $payroll->total_salary;
        $document_name = $payroll->employeePosition->employee->id  . $payroll->employeePosition->position->id . $payroll->id;
        $html = View::make('payroll.payment_detail_pdf', compact('base_salary', 'overtime_hours', 'absen', 'bonus_salary', 'overtime_cost', 'total_salary', 'document_name', 'payroll'))->render();

        $pdf = new Dompdf();
        $pdf->loadHtml($html);
        $pdf->setPaper('A4');

        $pdf->render();

        return $pdf->stream($document_name . '.pdf', ['Attachment' => false]);
    }
}

resources/views/payroll/create.blade.php
@extends('layout')
@section('title', 'Add New Payroll')
@section('content')
<div class="col-sm-12 col-xl-10">
  <div class="bg-secondary rounded h-100 p-4">
    <h6 class="mb-4"> Add New Payroll </h6>
    <h6>{{$employee_position->employee->name}} - {{$employee_position->position->name}}</h6> <br>
    <form method="POST" action="{{route('payrolls.store')}}">
      @csrf
      {{ method_field('POST') }}
      {{ csrf_field() }}
      <div class="row">
        <div class="mb-3 col-6">
          <label for="name" class="form-label">Month</label>
          <select class="form-select" id="floatingSelect" aria-label="Floating label select example" name="month">
            <option selected>Select Month</option>
            <option value="1">January</option>
            <option value="2">February</option>
            <option value="3">March</option>
            <option value="4">April</option>
            <option value="5">May</option>
            <option value="6">June</option>
            <option value="7">Jully</option>
            <option value="8">August</option>
            <option value="9">September</option>
            <option value="10">October</option>
            <option value="11">November</option>
            <option value="12">December</option>
          </select>
          <input type="hidden" name="employee_position_id" value="{{$employee_position->id}}">
        </div>
        <div class="mb-3 col-6">
          <label for="year" class="form-label">Year</label>
          <input type="number" class="form-control" id="year" name="year">
        </div>
      </div>
      <div class="row">
        <div class="mb-3 col-6">
          <label for="absen" class="form-label">Absen</label>
          <input type="number" class="form-control" id="absen" name="absen" placeholder="check at employee attendances data">
        </div>
        <div class="mb-3 col-6">
          <label for="present" class="form-label">Present</label>
          <input type="number" class="form-control" id="present" name="present" placeholder="check at employee attendances data">
        </div>
      </div>
      <div class="row">
        <div class="mb-3 col-4">
          <label for="overtimeHours" class="form-label">Overtime Hours</label>
          <input type="number" class="form-control" id="overtimeHours" name="overtime_hours">
        </div>
        <div class="mb-3 col-4">
          <label for="bonusSalary" class="form-label">Bonus Salary</label>
          <input type="number" class="form-control" id="bonusSalary" name="bonus_salary">
        </div>
        <div class="mb-3 col-4">
          <label for="deduction" class="form-label">Deduction</label>
          <input type="number" class="form-control" id="deduction" name="deduction">
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Save and Calculate Salary</button>
    </form>
  </div>
</div>
@endsection

resources/views/payroll/index.blade.php
@extends('layout')
@section('title', 'Employee Position List')
@section('content')
<div class="text-center rounded p-4" style="background-color:whitesmoke;">
  <div class="d-flex align-items-center justify-content-between mb-4">
    <h6 class="mb-0" style="color: slategray;">Employee Position List</h6>
  </div>
  <div class="table-responsive">
    <table class="table text-start align-middle table-hover mb-0 my-table">
      <thead>
        <tr>
          <th>Employee Name</th>
          <th>Position</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($employee_positions as $employee_position)
        <tr>
          <td>{{$employee_position->employee->name}}</td>
          <td>{{$employee_position->position->name}}</td>
          <td>
            @if(Auth::user()->role == 'admin')
            <a class="btn btn-warning btn-sm" href="{{ route('payrolls.add', $employee_position->id) }}">
              <i class="fa fa-plus"></i> Add Payroll
            </a>
            @endif
            @if ($employee_position->payrolls->count() > 0)
            <a class="btn btn-success btn-sm" href="{{ route('payrolls.show', $employee_position->id) }}">
              <i class="fa fa-eye">View Payrolls</i>
            </a>
            @elseif ($employee_position->payrolls->count() < 1 && Auth::user()->role == 'employee')
            <i>Payroll for this position has not been created</i>
            @endif

          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection

@push('scripts')
@if(session('success'))
<script>
  Swal.fire({
    icon: 'success',
    title: 'Success',
    text: "{{ session('success') }}",
  });
</script>
@endif
<script>
  $(document).ready(function() {
    $('.my-table').DataTable();
  });
</script>
@endpush

resources/views/payroll/payment_detail_pdf.blade.php
<html>

<head>
  <title>Salary Slip</title>
  <style>
    th {
      text-align: left;
    }

    .right {
      text-align: right;
    }
  </style>
</head>
<h3 style="text-align: center;">Salary Slip {{$document_name}}</h3>
<br> <br>
<div style="border: 1px solid black; padding:20px">
  <table style="border: 0px; width: 100%;">
    <thead>
      <tr>
        <th><b>Employee Details</b></th>
        <th>Salary Slip: {{$document_name}}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{$payroll->employeePosition->employee->name}}</td>
        <td>Issued Date: {{$payroll->payment_date}}</td>
      </tr>
      <tr>
        <td><i>{{$payroll->employeePosition->position->name}}</i></td>
        <td>Salary for: {{$payroll->year}}/{{$payroll->month}}</td>
      </tr>
      <tr>
        <td></td>
        <td>Absence: {{$payroll->absen}} days</td>
      </tr>
    </tbody>
  </table>
  <h4>Salary Details</h4>
  <table style="border: 0px; width: 100%;">
    <thead>
      <tr>
        <th><b>Description</b></th>
        <th class="right"><b>Total</b></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>BASE SALARY</td>
        <td class="right">{{'Rp ' . number_format($base_salary, 0, ',', '.')}}</td>
      </tr>
      <tr>
        <td>Bonus Salary</td>
        <td class="right">{{'Rp ' . number_format($bonus_salary, 0, ',', '.')}}</td>
      </tr>
      <tr>
        <td>Absence</td>
        <td class="right">{{'Rp ' . number_format($absen/20 * $base_salary, 0, ',', '.')}}</td>
      </tr>
      <tr>
        <td>Overtime</td>
        <td class="right">{{'Rp ' . number_format($overtime_hours*$overtime_cost, 0, ',', '.')}}</td>
      </tr>
      <tr>
        <td>Deduction</td>
        <td class="right">{{'Rp ' . number_format($payroll->deduction, 0, ',', '.')}}</td>
      </tr>
      <tr>
        <td><b>Total Salary</b></td>
        <td class="right"><b>{{'Rp ' . number_format($total_salary, 0, ',', '.')}}</b></td>
      </tr>
    </tbody>
  </table>
</div>

</html>

resources/views/payroll/show.blade.php
@extends('layout')
@section('title', 'Payroll List')
@section('content')
<div class="text-center rounded p-4" style="background-color:whitesmoke;">
  <div class="d-flex align-items-center justify-content-between mb-4">
    <h6 class="mb-0" style="color: slategray;">Payroll List {{$first_payroll->employeePosition->employee->name}} - {{$first_payroll->employeePosition->position->name}} </h6>
  </div>
  <div class="table-responsive">
    <table class="table text-start align-middle table-hover mb-0 my-table">
      <thead>
        <tr>
          <th>Month</th>
          <th>Base <br> Salary</th>
          <th>Overtime<br>Hours</th>
          <th>Deduction</th>
          <th>Absen</th>
          <th>Bonus<br>Salary</th>
          <th>Total<br>Salary</th>
          <th>Status</th>
          <th>Payment<br>Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($payrolls as $payroll)
        <tr>
          @php
          $bonus_salary = $payroll->bonus_salary;
          $deduction = $payroll->deduction;
          $total_salary = $payroll->total_salary;
          $base_salary = $payroll->EmployeePosition->position->base_salary;
          $baseSalaryFormat = 'Rp ' . number_format($base_salary, 0, ',', '.');
          $totalSalaryFormat = 'Rp ' . number_format($total_salary, 0, ',', '.');
          $bonusSalaryFormat = 'Rp ' . number_format($bonus_salary, 0, ',', '.');
          $deductionFormat = 'Rp ' . number_format($deduction, 0, ',', '.');
          @endphp
          <td>{{$payroll->year}}-{{$payroll->month}}</td>
          <td>{{$baseSalaryFormat}}</td>
          <td>{{$payroll->overtime_hours}} hours</td>
          <td>{{$deductionFormat}}</td>
          <td>{{$payroll->absen}} days</td>
          <td>{{$bonusSalaryFormat}}</td>
          <td>{{$totalSalaryFormat}}</td>
          <td>{{$payroll->status}}</td>
          @if(isset($payroll->payment_date))
          <td>{{$payroll->payment_date}}</td>
          @else
          <td class="text-center">-</td>
          @endif
          <td>
            @if($payroll->status == 'pending' && Auth::user()->role == 'admin')
            <form style="display: inline-block;" method="POST" onsubmit="return confirm('Are you sure want to pay the salary?')" action="{{route('payrolls.pay_salary', $payroll->id)}}">
              {{ csrf_field() }}
              {{ method_field('POST') }}
              <button type="submit" class="btn btn-success btn-sm" href="">
                <i class="fa fa-money-bill"> Pay Salary</i>
              </button>
            </form>
            <br>
            <a class="btn btn-warning btn-sm" href="{{ route('payrolls.edit', $payroll->id) }}">
              <i class="fa fa-plus"></i>Edit Payroll
            </a>
            <form style="display: inline-block;" method="POST" onsubmit="return confirm('Apakah kamu yakin untuk menghapus data ini?')" action="{{route('payrolls.destroy', $payroll->id)}}">
              {{ csrf_field() }}
              {{ method_field('DELETE') }}
              <button type="submit" class="btn btn-danger btn-sm">
                <i class="fa fa-trash"></i>
              </button>
            </form>
            @endif
            @if($payroll->status == 'paid')
            <a class="btn btn-success btn-sm" href="{{route('payrolls.payment_detail_pdf', $payroll->id)}}">
              <i class="fa fa-eye"> Payment Detail</i>
            </a>
            @elseif($payroll->status == 'pending' && Auth::user()->role == 'employee')
            <b><p>Salary is being processed</p></b>
            @endif
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection
@push('scripts')
<script>
  $(document).ready(function() {
    $('.my-table').DataTable();
  });
</script>
@endpush