routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware('auth')->group(function () {
  Route::get('payrolls/payment_detail_pdf/{id}', [App\Http\Controllers\PayrollController::class, 'paymentDetailPdf'])->name('payrolls.payment_detail_pdf');
  Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('index');
  Route::resource('employees', App\Http\Controllers\EmployeeController::class);
  Route::resource('positions', App\Http\Controllers\PositionController::class);
  Route::get('payrolls/add/{id}', [App\Http\Controllers\PayrollController::class, 'addPayroll'])->name('payrolls.add');
  Route::post('payrolls/pay_salary/{id}', [App\Http\Controllers\PayrollController::class, 'paySalary'])->name('payrolls.pay_salary');
  Route::get('payrolls/payment_detail_pdf/{id}', [App\Http\Controllers\PayrollController::class, 'paymentDetailPdf'])->name('payrolls.payment_detail_pdf');
  Route::resource('payrolls', App\Http\Controllers\PayrollController::class);
  Route::resource('attendances', App\Http\Controllers\AttendanceController::class);
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Position;


class Employee extends Model
{
    use HasFactory;
    protected $guarded = [];


    public function user()
    {
        return $this->belongsTo(User::class)->withDefault([
            'name' => '-',
        ]);
    }

    public function attendances()
    {
        return $this->hasMany(Attendance::class);
    }
    

    public function positions()
    {
        return $this->belongsToMany(Position::class, 'employee_position', 'employee_id', 'position_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Position;
use App\Models\User;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $employees = Employee::with('positions')->get();
        return view('employee.index', compact('employees'));
    }

    public function create()
    {
        $positions = Position::all();
        $users = User::where('role', 'employee')->get();
        return view('employee.create', compact('positions', 'users'));
    }

    public function store(Request $request)
    {
        $formattedBirthDate = Carbon::createFromFormat('m/d/Y', $request->birth_date)->format('Y-m-d');
        $employee =  Employee::create([
            'name' => $request->name,
            'birth_date' => $formattedBirthDate,
            'address' => $request->address,
            'phone_number' => $request->phone_number,
            'user_id' => $request->user_id
        ]);

        $positionIds = $request->input('positions', []); // Assuming positions input is an array of position IDs
        $employee->positions()->attach($positionIds);

        $user = User::find($request->user_id);
        $user->employee_id = $employee->id;
        $user->save();

        session()->flash('success', 'Employee Data created successfully.');
        return redirect()->route('employees.index');
    }

    public function edit($id)
    {
        $employee = Employee::find($id);
        $positions = Position::all();
        $users = User::where('role', 'employee')->get();
        $employee_positions = $employee->positions;

        return view('employee.edit', compact('employee', 'employee_positions', 'positions', 'users'));
    }

    public function update(Request $request, $id)
    {
        $format = 'Y-m-d';
        $dateTime = DateTime::createFromFormat($format, $request->birth_date);
        $isCorrectFormat = ($dateTime !== false && $dateTime->format($format) === $request->birth_date);
        if ($isCorrectFormat) {
            $formattedBirthDate = $request->birth_date;
        } else {
            $formattedBirthDate = Carbon::createFromFormat('m/d/Y', $request->birth_date)->format('Y-m-d');
        }

        $employee = Employee::find($id);
        $employee->name = $request->name;
        $employee->address = $request->address;
        $employee->birth_date = $formattedBirthDate;
        $employee->phone_number = $request->phone_number;
        $employee->user_id = $request->user_id;

        $positionIds = $request->input('positions', []);
        $employee->positions()->sync($positionIds);
        $employee->save();

        $user = User::find($request->user_id);
        $user->employee_id = $employee->id;
        $user->save();
        session()->flash('success', 'Employee edited successfully.');
        return redirect()->route('employees.index');
    }

    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->positions()->detach();
        $employee->delete();

        return redirect()->route('employees.index');
    }
}

resources/views/employee/create.blade.php
@extends('layout')
@section('title', 'Add New Employee')
@section('content')

<div class="col-sm-12 col-xl-12">
  <div class="bg-secondary rounded h-100 p-4">
    <h6 class="mb-4"> Add New Employee</h6>
    <form method="POST" action="{{route('employees.store')}}">
      @csrf
      {{ method_field('POST') }}
      {{ csrf_field() }}
      <div class="mb-3">
        <label for="name" class="form-label">Employee Name</label>
        <input type="text" class="form-control" id="name" name="name">
      </div>
      <div class="mb-3">
        <label for="phoneNumber" class="form-label">Phone Number</label>
        <input type="number" class="form-control" id="phoneNumber" name="phone_number">
      </div>
      <div class="mb-3">
        <label for="overtimeCost" class="form-label">Birth Date</label>
        <input type="text" class="form-control datepicker" data-provide="datepicker" id="birthDate" name="birth_date">
      </div>
      <div class="mb-3">
        <label for="overtimeCost" class="form-label">Address</label>
        <textarea id="address" name="address" class="form-control"></textarea>
      </div>
      <div class="mb-3">
        <label class="form-label">Employee Position</label>
        @foreach($positions as $position)
        <div class="form-check">
          <input class="form-check-input" name="positions[]" type="checkbox" value="{{$position->id}}" id="flexCheckDefault">
          <label class="form-check-label" for="flexCheckDefault">
            {{$position->name}}
          </label>
        </div>
        @endforeach
      </div>
      <div class="mb-3">
        <label for="user_id" class="form-label">Integrated with user:</label>
        <select name="user_id" class="form-select" id="floatingSelect">
          <option>Select user you'd like to integrated with</option>
          @foreach($users as $user)
          <option value="{{$user->id}}">{{$user->name}} - {{$user->email}}</option>
          @endforeach
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Save Employee</button>
    </form>
  </div>
</div>
@endsection

<script>
  $(document).ready(function() {
    $('.datepicker').datepicker({
      format: 'yyyy-mm-dd', // Set the desired date format
      autoclose: true, // Close the datepicker when a date is selected
    });
  });
</script>

resources/views/employee/edit.blade.php
@extends('layout')
@section('title', 'Edit Employee')
@section('content')

<div class="col-sm-12 col-xl-12">
  <div class="bg-secondary rounded h-100 p-4">
    <h6 class="mb-4"> Edit Employee</h6>
    <form method="POST" action="{{route('employees.update', $employee->id)}}">
      @csrf
      {{ method_field('PUT') }}
      {{ csrf_field() }}
      <div class="mb-3">
        <label for="name" class="form-label">Employee Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{$employee->name}}">
      </div>
      <div class="mb-3">
        <label for="phoneNumber" class="form-label">Phone Number</label>
        <input type="number" class="form-control" id="phoneNumber" name="phone_number" value="{{$employee->phone_number}}">
      </div>
      <div class="mb-3">
        <label for="overtimeCost" class="form-label">Birth Date</label>
        <input type="text" class="form-control datepicker" data-provide="datepicker" id="birthDate" name="birth_date" value="{{$employee->birth_date}}">
      </div>
      <div class="mb-3">
        <label for="overtimeCost" class="form-label">Address</label>
        <textarea id="address" name="address" class="form-control">{{$employee->address}}</textarea>
      </div>
      <div class="mb-3">
        <label class="form-label">Employee Position</label>
        @foreach($positions as $position)
        <div class="form-check">
          <input class="form-check-input" name="positions[]" type="checkbox" value="{{$position->id}}" id="flexCheckDefault" {{ in_array($position->id, old('positions', $employee_positions->pluck('id')->toArray())) ? 'checked' : '' }}>
          <label class="form-check-label" for="flexCheckDefault">
            {{$position->name}}
          </label>
        </div>
        @endforeach
      </div>
      <div class="mb-3">
        <label for="user_id" class="form-label">Integrated with user:</label>
        <select name="user_id" class="form-select" id="floatingSelect">
          <option>Select user you'd like to integrated with</option>
          @foreach($users as $user)
          <option value="{{$user->id}}" {{ old('user_id', $employee->user_id) == $user->id ? 'selected' : '' }}>{{$user->name}} - {{$user->email}}</option>
          @endforeach
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Update Employee</button>
    </form>
  </div>
</div>
@endsection

<script>
  $(document).ready(function() {
    $('.datepicker').datepicker({
      format: 'yyyy-mm-dd', // Set the desired date format
      autoclose: true, // Close the datepicker when a date is selected
    });
  });
</script>

resources/views/employee/index.blade.php
@extends('layout')
@section('title', 'Employee List')
@section('content')
<div class="col-sm-12 col-xl-12" style="margin-bottom: 10px;">
  <div class="bg-secondary rounded h-100 p-4">
    <a href="{{route('employees.create')}}" class="btn btn-light m-2">
      <i class="fa fa-plus"></i> Add New Employee
    </a>
  </div>
</div>
<div class="text-center rounded p-4" style="background-color:whitesmoke;">
  <div class="d-flex align-items-center justify-content-between mb-4">
    <h6 class="mb-0" style="color: slategray;">Employee List</h6>
  </div>
  <div class="table-responsive">
    <table class="table text-start align-middle table-hover mb-0 my-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Position</th>
          <th>Phone Number</th>
          <th>Birth Date</th>
          <th>Address</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($employees as $employee)
        <tr>
          <td>{{$employee->name}}</td>
          <td>
            @foreach($employee->positions as $position)
            {{$position->name}} <br>
            @endforeach
          </td>
          <td>{{$employee->phone_number}}</td>
          <td>{{$employee->birth_date}}</td>
          <td>{{$employee->address}}</td>
          <td>
            <a class="btn btn-success btn-sm" href="{{ route('attendances.show', $employee->id) }}">
              <i class="fa fa-eye">View Attendances</i>
            </a>
            <a class="btn btn-warning btn-sm" href="{{ route('employees.edit', $employee->id) }}">
              <i class="fa fa-edit"></i>
            </a>
            <form style="display: inline-block;" method="POST" onsubmit="return confirm('Apakah kamu yakin untuk menghapus data ini?')" action="{{route('employees.destroy', $employee->id)}}">
              {{ csrf_field() }}
              {{ method_field('DELETE') }}
              <button type="submit" class="btn btn-danger btn-sm">
                <i class="fa fa-trash"></i>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection
@push('scripts')
@if(session('success'))
<script>
  Swal.fire({
    icon: 'success',
    title: 'Success',
    text: "{{ session('success') }}",
  });
</script>
@endif

<script>
  $(document).ready(function() {
    $('.my-table').DataTable();
  });
</script>
@endpush